services:
  mysql:
    image: mysql:8
    container_name: redditclone-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./internal/mysql:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:6
    container_name: redditclone-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
