// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	post "redditclone/pkg/post"

	mock "github.com/stretchr/testify/mock"
)

// RepoPost is an autogenerated mock type for the RepoPost type
type RepoPost struct {
	mock.Mock
}

// AddComment provides a mock function with given fields: postID, comment
func (_m *RepoPost) AddComment(postID string, comment post.Comment) (*post.Post, error) {
	ret := _m.Called(postID, comment)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 *post.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(string, post.Comment) (*post.Post, error)); ok {
		return rf(postID, comment)
	}
	if rf, ok := ret.Get(0).(func(string, post.Comment) *post.Post); ok {
		r0 = rf(postID, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(string, post.Comment) error); ok {
		r1 = rf(postID, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddVote provides a mock function with given fields: postID, vote
func (_m *RepoPost) AddVote(postID string, vote post.Voting) (*post.Post, error) {
	ret := _m.Called(postID, vote)

	if len(ret) == 0 {
		panic("no return value specified for AddVote")
	}

	var r0 *post.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(string, post.Voting) (*post.Post, error)); ok {
		return rf(postID, vote)
	}
	if rf, ok := ret.Get(0).(func(string, post.Voting) *post.Post); ok {
		r0 = rf(postID, vote)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(string, post.Voting) error); ok {
		r1 = rf(postID, vote)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelVote provides a mock function with given fields: postID, user
func (_m *RepoPost) CancelVote(postID string, user string) (*post.Post, error) {
	ret := _m.Called(postID, user)

	if len(ret) == 0 {
		panic("no return value specified for CancelVote")
	}

	var r0 *post.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*post.Post, error)); ok {
		return rf(postID, user)
	}
	if rf, ok := ret.Get(0).(func(string, string) *post.Post); ok {
		r0 = rf(postID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(postID, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: _a0
func (_m *RepoPost) Create(_a0 *post.Post) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*post.Post) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: postID
func (_m *RepoPost) Delete(postID string) error {
	ret := _m.Called(postID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *RepoPost) GetAll() []*post.Post {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*post.Post
	if rf, ok := ret.Get(0).(func() []*post.Post); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*post.Post)
		}
	}

	return r0
}

// GetByCategory provides a mock function with given fields: category
func (_m *RepoPost) GetByCategory(category string) []*post.Post {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for GetByCategory")
	}

	var r0 []*post.Post
	if rf, ok := ret.Get(0).(func(string) []*post.Post); ok {
		r0 = rf(category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*post.Post)
		}
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *RepoPost) GetByID(id string) (*post.Post, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *post.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*post.Post, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *post.Post); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUser provides a mock function with given fields: username
func (_m *RepoPost) GetByUser(username string) []*post.Post {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []*post.Post
	if rf, ok := ret.Get(0).(func(string) []*post.Post); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*post.Post)
		}
	}

	return r0
}

// RemoveComment provides a mock function with given fields: postID, commentID
func (_m *RepoPost) RemoveComment(postID string, commentID string) (*post.Post, error) {
	ret := _m.Called(postID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveComment")
	}

	var r0 *post.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*post.Post, error)); ok {
		return rf(postID, commentID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *post.Post); ok {
		r0 = rf(postID, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(postID, commentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepoPost creates a new instance of RepoPost. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoPost(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoPost {
	mock := &RepoPost{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
